/* Automatically generated nanopb header */
/* Generated by nanopb-0.3.9.2 at Mon Dec 17 23:17:15 2018. */

#ifndef PB_ARDUINO_ARDUINODESCRIPTOR_PB_H_INCLUDED
#define PB_ARDUINO_ARDUINODESCRIPTOR_PB_H_INCLUDED
#include "pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Struct definitions */
typedef struct _arduino_ArduinoDescriptor {
    int32_t sequence;
    int32_t axis[8];
    bool button[32];
/* @@protoc_insertion_point(struct:arduino_ArduinoDescriptor) */
} arduino_ArduinoDescriptor;

/* Default values for struct fields */

/* Initializer values for message structs */
#define arduino_ArduinoDescriptor_init_default   {0, {0, 0, 0, 0, 0, 0, 0, 0}, {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}}
#define arduino_ArduinoDescriptor_init_zero      {0, {0, 0, 0, 0, 0, 0, 0, 0}, {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}}

/* Field tags (for use in manual encoding/decoding) */
#define arduino_ArduinoDescriptor_sequence_tag   1
#define arduino_ArduinoDescriptor_axis_tag       2
#define arduino_ArduinoDescriptor_button_tag     3

/* Struct field encoding specification for nanopb */
extern const pb_field_t arduino_ArduinoDescriptor_fields[4];

/* Maximum encoded size of messages (where known) */
#define arduino_ArduinoDescriptor_size           163

/* Message IDs (where set with "msgid" option) */
#ifdef PB_MSGID

#define ARDUINODESCRIPTOR_MESSAGES \


#endif

#ifdef __cplusplus
} /* extern "C" */
#endif
/* @@protoc_insertion_point(eof) */

#endif
