/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.9.2 at Sun Dec 16 17:31:06 2018. */

#include "ArduinoDescriptor.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t arduino_ArduinoDescriptor_fields[2] = {
    PB_FIELD(  1, INT32   , SINGULAR, STATIC  , FIRST, arduino_ArduinoDescriptor, button, button, 0),
    PB_LAST_FIELD
};


/* @@protoc_insertion_point(eof) */
